src/Entity/Item.php
<?php

namespace App\Entity;

use App\Repository\ItemRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ItemRepository::class)
 */
class Item
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $codeDgs;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=180, nullable=true)
     */
    private $urlDiscoGs;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $year;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $mediaStatus;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $caseStatus;

    /**
     * @ORM\Column(type="integer", nullable=true )
     */
    private $numForSale;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default": 0.0} )
     */
    private $peopleWantIt;



    /**
     * @ORM\Column(type="string", length=100)
     */
    private $catalogCode;

    /**
     * @ORM\Column(type="string", length=180, nullable=true )
     */
    private $recommendPriceDgs;

    /**
     * @ORM\Column(type="string", length=180, nullable=true )
     */
    private $PriceSale;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default": 0} )
     */
    private $sold;

    /**
     * @ORM\ManyToOne(targetEntity="Lote", inversedBy="items")
     **/
    private $lote;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeDgs(): ?string
    {
        return $this->codeDgs;
    }

    public function setCodeDgs(string $codeDgs): self
    {
        $this->codeDgs = $codeDgs;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMediaStatus(): ?string
    {
        return $this->mediaStatus;
    }

    public function setMediaStatus(string $mediaStatus): self
    {
        $this->mediaStatus = $mediaStatus;

        return $this;
    }

    public function getCaseStatus(): ?string
    {
        return $this->caseStatus;
    }

    public function setCaseStatus(string $caseStatus): self
    {
        $this->caseStatus = $caseStatus;

        return $this;
    }

    public function getCatalogCode(): ?string
    {
        return $this->catalogCode;
    }

    public function setCatalogCode(string $catalogCode): self
    {
        $this->catalogCode = $catalogCode;

        return $this;
    }

    public function getRecommendPriceDgs(): ?string
    {
        return $this->recommendPriceDgs;
    }

    public function setRecommendPriceDgs(string $recommendPriceDgs): self
    {
        $this->recommendPriceDgs = $recommendPriceDgs;

        return $this;
    }

    public function getLote(): ?Lote
    {
        return $this->lote;
    }

    public function setLote(?Lote $lote): self
    {
        $this->lote = $lote;

        return $this;
    }

    public function getNumForSale(): ?int
    {
        return $this->numForSale;
    }

    public function setNumForSale(int $numForSale): self
    {
        $this->numForSale = $numForSale;

        return $this;
    }

    public function getPeopleWantIt(): ?bool
    {
        return $this->peopleWantIt;
    }

    public function setPeopleWantIt(bool $peopleWantIt): self
    {
        $this->peopleWantIt = $peopleWantIt;

        return $this;
    }

    public function getUrlDiscoGs(): ?string
    {
        return $this->urlDiscoGs;
    }

    public function setUrlDiscoGs(string $urlDiscoGs): self
    {
        $this->urlDiscoGs = $urlDiscoGs;

        return $this;
    }

    public function getYear(): ?string
    {
        return $this->year;
    }

    public function setYear(string $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getPriceSale(): ?string
    {
        return $this->PriceSale;
    }

    public function setPriceSale(?string $PriceSale): self
    {
        $this->PriceSale = $PriceSale;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }
}

templates/_parts/_flash_message.html.twig
{% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
{% endfor %}
{% for message in app.flashes('danger') %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
{% endfor %}

templates/_parts/_form_price_sale.html.twig
<div class="boxPrice boxPriceSale-{{ item.id }}"  style="display: block;"
      data-iditem="{{ item.id }}">{{ item.priceSale|number_format(2, ',', '.') }}
  <span class="viewFormPrice" ><i class="fas fa-edit text-gray-300 ml-2"></i></a>
</div>
<div class="formsprice formPriceSale-{{ item.id }}" style="display: none;">
    <form action="{{ url('item_change_pricesale') }}" method="POST" >
      <input type="text" class="changePriceSale" name="priceSale"
            value="{{ item.priceSale|number_format(2, ',', '.') }}" />
      <input type="hidden" value="{{ item.id }}" name="idItem" />
      <input type="hidden" value="{{ placePriceSale }}" name="place" />
    </form>
    <div class="closePrice"  data-closeprice="{{ item.id }}">
      <i class="fas fa-times text-gray-300 ml-2"></i>
    </div>
</div>

templates/_parts/footer.html.twig
<footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Control Discos</span>
          </div>
        </div>
</footer>

templates/_parts/sidebar.html.twig
<!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-secondary sidebar sidebar-dark accordion bg-gradient-primary-es" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url('home') }}">
        <div class="sidebar-brand-icon">
          <img src="{{ asset('assets/img/logo.png')}}" alt="logo" />
        </div>
        <div class="sidebar-brand-text mx-2">Control Discos</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{{ url('home') }}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Control Proyectos
      </div>

      <li class="nav-item">
        <a class="nav-link" href="{{url('lote_index', {'filterlotestatus': 'all', 'filterloteinteres' : 'all',
                                                       'sortcolumn': 'id', 'sortdirection' : 'DESC'}) }}">
          <i class="fas fa-boxes"></i>
          <span>Lotes</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{{url('inventory_list', {'filter': 'all', 'filterlote': 0}) }}">
          <i class="fas fa-compact-disc"></i>
          <span>Inventario</span>
        </a>
      </li>





     {% if is_granted('ROLE_SUPER_ADMIN')  %}

      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Administración
      </div>

      <li class="nav-item">
           <a class="nav-link" href="{{ url('origin_index') }}">
          <i class="fas fa-map-marker-alt"></i>
          <span>Origen Lotes</span>
        </a>

      </li>


      <li class="nav-item">
            <a class="nav-link" href="{{ url('imported_inventory')}}">
          <i class="fas fa-cloud-upload-alt"></i>
          <span>Importar datos </span>
        </a>

      </li>

      <li class="nav-item">
           <a class="nav-link" href="{{ url('user_index') }}">
          <i class="fas fa-users"></i>
          <span>Listado usuarios</span>
        </a>

      </li>

   {% endif %}

      <hr class="sidebar-divider">



      <li class="nav-item">
        <a class="nav-link" href="{{ url('app_logout') }}">
          <i class="fas fa-sign-out-alt"></i>
          <span>Desconectar</span>
        </a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>


    <!-- End of Sidebar -->

templates/_parts/top-nav.html.twig
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <ul class="navbar-nav ml-auto">
    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ app.user.email }}</span>
        <div class="img-profile rounded-circle bg-light border border-{{ app.user.roles[0] }}" >
        <i class="fas fa-user text-{{ app.user.roles[0] }} pt-2 pl-2"></i>
      </div>
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">
        <a  class="dropdown-item float-right" > <i class="fas fa-user ext-gray-400 mr-2"></i>
        {{ app.user.roles[0] }}</a>
        <a class="dropdown-item" href="{{ url('app_logout') }}" >
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Desconectar
        </a>
      </div>
    </li>

  </ul>

</nav>